spring:
  application:
    name: guohao
  datasource:
    url: jdbc:mysql://localhost:3307/partner?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://47.95.177.52:3307/partner?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #password: YourNewPassword
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: 5
      # 连接池最大连接数
      maximum-pool-size: 15
      # 空闲连接最大存活时间，默认600000(10分钟)
      idle-timeout: 180000
      # 连接最大存活时间，默认1800000(30分钟)
      max-lifetime: 1800000
      # 连接超时时间，默认30000(30秒)
      connection-timeout: 30000
      # 用于测试连接是否可用的查询语句
      connection-test-query: SELECT 1
      # 自动提交
      auto-commit: true
      # 连接池名称
      pool-name: HikariCP
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException
      validation-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
      timeout: 1000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/partner/mapper/*.xml
  type-aliases-package: com.partner.entity

aliyun:
  oss:
    bucketName: guohaodashabi
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing

logging:
  level:
    okhttp3: info